;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="WFC.Hex.Empty",NewTagName="WFC.Hex.EmptyEdge")
+GameplayTagRedirects=(OldTagName="WFC.Hex.FixedEmpty",NewTagName="WFC.Hex.FixedEmptyEdge")
+GameplayTagRedirects=(OldTagName="WFC.Hex.UndergroundCity.HEdge.Normal",NewTagName="WFC.Hex.UndergroundCity.HEdge.Ground")
+GameplayTagList=(Tag="Test.StateTree.Tag4",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.EmptyEdge",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.EmptyTile",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.FixedEmptyEdge",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.FixedEmptyTile",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.SkyCity.Edge.Side.Bridge",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.SkyCity.Edge.Side.Floor",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.SkyCity.Edge.Side.FloorHalf",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.SkyCity.Edge.UpDown.Tower",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.SkyCity.Tile.Bridge",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.SkyCity.Tile.Floor",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.SkyCity.Tile.Tower",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.SkyCity.Tile.TowerTop",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.Air",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.Bridge",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.Ground",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.Ground.Inner",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.Ground.Outer",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.OpenFloorInner",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.Soild",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.WallA",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.WallB",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.WallC",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.WallD",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.Waterway.A",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.Waterway.B",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.Waterway.C",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.HEdge.Waterway.End",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Air",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgeBottom.aaaaaa",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgeBottom.saaaaa",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgeBottom.sasaaa",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgeBottom.ssaaaa",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgeBottom.sssaaa",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgeBottom.ssssaa",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgeBottom.sssssa",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgePillar.baaaaa",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgePillar.bbaaaa",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgePillar.bbbaaa",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgePillar.bbbbaa",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgePillar.bbbbba",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.BridgePillar.bbbbbb",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.Main.aaaabb",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.Main.aaabbb",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.Main.aabbbb",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.Main.abbbbb",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Bridge.Main.bbbbbb",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Ground",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Ground.InnerGroundTD",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Ground.OuterGroundD",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.OpenFloor.OpenFloorHalfD",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.OpenFloor.OpenFloorTD",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Soild",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Stair.SpiralStair",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Stair.StraightStair",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.LargeWall",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.LargeWallBranch",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.LargeWallBranchRoof",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.LargeWallD",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.LargeWallDoorD",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.LargeWallMidBranch1",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.LargeWallMidBranch2",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.LargeWallMidBranch1Roof",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.LargeWallMidBranch2Roof",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.LargeWallRoof",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.SmallWall",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.SmallWallBranch",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.SmallWallBranchRoof",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.SmallWallD",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.SmallWallRoof",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.SmallWallWindow",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.SmallWallWindowD",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.WallCorner",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.WallCornerD",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Wall.WallCornerRoof",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Waterway.WaterwayCorner",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Waterway.WaterwayCorner2",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Waterway.WaterwayCorner2Rail",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Waterway.WaterwayCornerLong",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Waterway.WaterwayCornerLongRail",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Waterway.WaterwayCornerRail",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Waterway.WaterwayEndPart1",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Waterway.WaterwayEndPart2",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Waterway.WaterwayEndPart1Rail",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.Tile.Waterway.WaterwayEndPart2Rail",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.Air",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.LargeWall",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.LargeWallBranch",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.LargeWallBranchRe",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.LargeWallMidBranch1",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.LargeWallMidBranch2",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.LargeWallMidBranch1Re",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.OpenFloor.Half",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.OpenFloor.Main",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.SmallWall",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.SmallWallBranch",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.Solid",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.WallCorner",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.Waterway.EndP1",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.Waterway.EndP2",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.Waterway.EndP1Re",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.Waterway.EndP2Re",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.Waterway.Half",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.Waterway.Large",DevComment="")
+GameplayTagList=(Tag="WFC.Hex.UndergroundCity.VEdge.Waterway.Small",DevComment="")

